# Builds test/fixtures/pre_signing.vault with the code as released before WI-079 (v0.8.1-alpha, commit
# 25508aa): unsigned boxes, uncommitted seals, no signing keys. It was generated by running this script from
# the app/ directory of an export of that commit (`mix run pre_signing.exs <path>`); it does not run against
# the current code. Passphrases are "pw-<member>" with 1,000 iterations (test-only).
alias FindependenceApp.{Session, Vault}
alias Findependence.{Household, Balances, Alignment}

act = fn v, m, fun ->
  {:ok, s} = Session.open(v, m, "pw-" <> m)

  case fun.(s.household) do
    {:ok, h} -> Session.save(%{s | household: h}).vault
    {:ok, h, _} -> Session.save(%{s | household: h}).vault
    other -> raise "op failed: #{inspect(other)}"
  end
end

v =
  Vault.create([{"ana", "pw-ana"}, {"ben", "pw-ben"}, {"cy", "pw-cy"}],
    iterations: 1_000,
    unsafe_test: true
  )
  |> act.(
    "ana",
    &Household.add_item(&1, "ana", "rent", %{note: "Rent", amount: -145_000, unit: :cents})
  )
  |> act.("ana", &Household.propose_grant(&1, "ana", "rent", "cy"))
  |> act.(
    "ana",
    &Household.add_item(&1, "ana", "car", %{note: "Car", amount: -31_000, unit: :cents})
  )
  |> act.("ana", &Household.propose_owners(&1, "ana", "car", ["ana", "ben"]))
  |> act.("ben", &Balances.add_debt(&1, "ben", "visa", "Visa", :card))
  |> act.(
    "ben",
    &Balances.add_reading(&1, "ben", "visa", %{
      on: "2026-08-27",
      balance: 540_000,
      rate_bp: 2199,
      min_payment: 16_000
    })
  )
  |> act.(
    "ben",
    &Balances.add_reading(&1, "ben", "visa", %{
      on: "2026-09-27",
      balance: 520_000,
      rate_bp: 2199,
      min_payment: 15_000
    })
  )
  |> act.("ben", &Household.propose_grant(&1, "ben", "visa", "ana"))
  |> act.("ana", &Alignment.add_value(&1, "ana", "home", "A safe home"))
  |> act.("ana", &Alignment.link(&1, "ana", "rent", "home"))
  |> act.("ben", &Household.relinquish(&1, "ben", "car"))

[path] = System.argv()
Vault.write!(v, path)
IO.puts("wrote #{path}: #{map_size(v.items)} items")
