defmodule FindependenceHostedWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :findependence_hosted

  # The session is stored in the cookie, signed and encrypted: it carries the session token and confirmation
  # messages, which can name an item (WI-085; ASSESS-002 FND-206).
  @session_options [
    store: :cookie,
    key: "_findependence_hosted_key",
    signing_salt: "04hgbOed",
    encryption_salt: "Hq2mR7vZ",
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:findependence_hosted, :secure_cookies, true)
  ]

  # only for the design specimen, which isn't routed in production (WI-085; ASSESS-002 FND-207)
  if Application.compile_env(:findependence_hosted, :specimen_route, false) do
    socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: @session_options]],
      longpoll: [connect_info: [session: @session_options]]
  end

  # Security headers first, so static files and errors carry them too (ARCH-001 9.4).
  plug FindependenceHostedWeb.SecurityHeaders

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :findependence_hosted,
    gzip: not code_reloading?,
    only: FindependenceHostedWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # forms at most 100 kB; a bring-in file at most 1 MB, on that route only (WI-073, WI-076)
  plug FindependenceHostedWeb.BodyParsers

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FindependenceHostedWeb.Router
end
