# SUPERSEDED by scripts/check (AUT-CHECK, WI-001) on 2026-09-25; retained for history (CHK-RUN-001). Do not use.
# Interim orientation check — NOT the registered AUT-CHECK automation (scripts/check).
#
# Generated by ACT-002 under project/bootstrap.yaml autonomy[deterministic_validation].
# Sources: framework/vocabulary/*.yaml, framework/states/machines.yaml,
#          framework/invariants/core.yaml, automation/workflows/bootstrap.yaml.
#
# A PASS here means only that none of the checks below failed. It does not
# satisfy the `check` requirement of any gate (see DEF-008), and it establishes
# no semantic, normative, Capability, Outcome, Purpose, or Telos truth.
#
# Usage (from repo root; first run fetches yaml_elixir from hex.pm):
#   elixir project/assurance/checks/orientation_check.exs

Mix.install([{:yaml_elixir, "~> 2.11"}])

defmodule OrientationCheck do
  @root Path.expand("../../..", __DIR__)

  def run do
    vocab = load!("framework/vocabulary/artifacts.yaml")
    rels = load!("framework/vocabulary/relationships.yaml")["relationships"]
    machines = load!("framework/states/machines.yaml")
    manifest = load!("project/manifest.yaml")
    {bootstrap, bootstrap_note} = load_bootstrap()

    types =
      (Enum.flat_map(vocab["foundational"], fn {_, ts} -> ts end) ++ vocab["derived"])
      |> MapSet.new()

    {artifacts, parse_results} = load_artifacts()
    by_id = Map.new(artifacts, &{&1["id"], &1})

    results =
      [
        {"C-00 bootstrap.yaml parses", bootstrap_note},
        {"C-01 project YAML parses", parse_results},
        {"C-02 I-001 unique stable ids", unique_ids(artifacts)},
        {"C-03 I-002 valid artifact types", valid_types(artifacts, types)},
        {"C-04 I-003 relationship typing and targets", rel_typing(artifacts, by_id, rels)},
        {"C-05 I-004 semantic hierarchy acyclic", acyclic(artifacts)},
        {"C-06 semantic/claim states valid", states(artifacts, machines)},
        {"C-07 I-012 no AI-canonicalized foundation", no_canonical(artifacts, manifest)},
        {"C-08 supplied wording preserved", wording(by_id, bootstrap)},
        {"C-09 I-008/I-010 evidence bound; integrity/applicability distinct",
         evidence(artifacts, by_id, machines)},
        {"C-10 I-020 generated artifacts identify sources", sources(artifacts)},
        {"C-11 WF-BOOTSTRAP postconditions", postconditions(manifest)}
      ]

    Enum.each(results, fn {name, r} -> report(name, r) end)

    failed = Enum.count(results, fn {_, r} -> match?({:fail, _}, r) end)
    IO.puts("\nartifacts checked: #{length(artifacts)}")
    IO.puts("RESULT: #{if failed == 0, do: "PASS", else: "FAIL (#{failed})"} (interim; not AUT-CHECK)")
    if failed > 0, do: System.halt(1)
  end

  defp report(name, :pass), do: IO.puts("PASS  #{name}")
  defp report(name, {:warn, msgs}), do: IO.puts("WARN  #{name}\n" <> lines(msgs))
  defp report(name, {:fail, msgs}), do: IO.puts("FAIL  #{name}\n" <> lines(msgs))
  defp lines(msgs), do: Enum.map_join(List.wrap(msgs), "\n", &"      - #{&1}")

  defp verdict([]), do: :pass
  defp verdict(errs), do: {:fail, errs}

  defp load!(rel), do: YamlElixir.read_from_file!(Path.join(@root, rel))

  # bootstrap.yaml is fenced in markdown (DEF-010); parse raw, then fall back to fence-stripped.
  defp load_bootstrap do
    path = Path.join(@root, "project/bootstrap.yaml")

    case YamlElixir.read_from_file(path) do
      {:ok, doc} ->
        {doc, :pass}

      {:error, e} ->
        stripped =
          path
          |> File.read!()
          |> String.split("\n")
          |> Enum.reject(&String.starts_with?(&1, "```"))
          |> Enum.join("\n")

        {YamlElixir.read_from_string!(stripped),
         {:warn, ["raw parse failed at line #{e.line} (#{e.type}); parsed with markdown fence stripped"]}}
    end
  end

  defp load_artifacts do
    files =
      Path.wildcard(Path.join(@root, "project/**/*.yaml"))
      |> Enum.reject(&(Path.basename(&1) in ["manifest.yaml", "bootstrap.yaml"]))

    Enum.reduce(files, {[], []}, fn f, {arts, errs} ->
      rel = Path.relative_to(f, @root)

      case YamlElixir.read_from_file(f) do
        {:ok, %{"artifacts" => list}} when is_list(list) ->
          {arts ++ Enum.map(list, &Map.put(&1, "__file", rel)), errs}

        {:ok, _} ->
          {arts, errs}

        {:error, e} ->
          {arts, ["#{rel}: #{inspect(e)}" | errs]}
      end
    end)
    |> then(fn {a, e} -> {a, verdict(e)} end)
  end

  defp unique_ids(arts) do
    arts
    |> Enum.frequencies_by(& &1["id"])
    |> Enum.filter(fn {id, n} -> n > 1 or is_nil(id) end)
    |> Enum.map(fn {id, n} -> "id #{inspect(id)} appears #{n}x" end)
    |> verdict()
  end

  defp valid_types(arts, types) do
    errs = for a <- arts, a["type"] not in types, do: "#{a["id"]}: unknown type #{inspect(a["type"])}"
    verdict(errs)
  end

  defp rels_of(a), do: a["relationships"] || []

  defp rel_typing(arts, by_id, rels) do
    errs = for a <- arts, r <- rels_of(a), err = rel_error(a, r, by_id, rels), do: err
    verdict(errs)
  end

  defp rel_error(a, %{"type" => t, "to" => to}, by_id, rels) do
    target = by_id[to]
    spec = rels[t]

    cond do
      is_nil(spec) -> "#{a["id"]}: unknown relationship #{t}"
      is_nil(target) -> "#{a["id"]} -#{t}-> #{to}: target does not exist"
      not allowed?(spec["from"], a["type"]) -> "#{a["id"]}: #{a["type"]} may not be source of #{t}"
      not allowed?(spec["to"], target["type"]) -> "#{a["id"]}: #{target["type"]} may not be target of #{t}"
      true -> nil
    end
  end

  defp allowed?(list, type), do: "*" in list or type in list

  @hierarchy ~w(concerns advances contributes_to enables realizes has_purpose)
  defp acyclic(arts) do
    edges =
      for a <- arts, r <- rels_of(a), r["type"] in @hierarchy, reduce: %{} do
        acc -> Map.update(acc, a["id"], [r["to"]], &[r["to"] | &1])
      end

    cyclic = Enum.filter(Map.keys(edges), &reaches?(edges, &1, &1, MapSet.new()))
    verdict(Enum.map(cyclic, &"#{&1} participates in a hierarchy cycle"))
  end

  defp reaches?(edges, from, goal, seen) do
    Enum.any?(Map.get(edges, from, []), fn n ->
      n == goal or (n not in seen and reaches?(edges, n, goal, MapSet.put(seen, n)))
    end)
  end

  @semantic_types ~w(Subject Telos Purpose Outcome Capability Function Mechanism Principle Context System DecisionScope)
  defp states(arts, m) do
    errs = for a <- arts, s = a["state"], s != nil, err = state_error(a, s, m), do: err
    verdict(errs)
  end

  defp state_error(%{"type" => "Claim"} = a, s, m),
    do: unless(s in m["claim"]["states"], do: "#{a["id"]}: invalid claim state #{s}")

  defp state_error(%{"type" => t} = a, s, m) when t in @semantic_types,
    do: unless(s in m["semantic"]["states"], do: "#{a["id"]}: invalid semantic state #{s}")

  defp state_error(_, _, _), do: nil

  defp no_canonical(arts, manifest) do
    foundation = manifest["canonical_foundation"] || %{}

    art_errs =
      for a <- arts, a["type"] in ~w(Subject Telos Purpose Principle), a["state"] == "canonical",
          not ratified?(a),
          do: "#{a["id"]} is canonical without a recorded human ratification"

    man_errs =
      for {k, v} <- foundation, v != nil, not ratified_ref?(arts, v),
          do: "manifest canonical_foundation.#{k} set without ratified artifact"

    verdict(art_errs ++ man_errs)
  end

  defp ratified?(a), do: get_in(a, ["ratification", "by"]) not in [nil, "ACT-002"]
  defp ratified_ref?(arts, id), do: Enum.any?(arts, &(&1["id"] == id and ratified?(&1)))

  defp norm(s) when is_binary(s), do: s |> String.split() |> Enum.join(" ")
  defp norm(_), do: nil

  defp wording(by_id, bootstrap) do
    inputs = bootstrap["foundation_inputs"]

    for {key, id} <- [{"subject", "SUBJ-001"}, {"telos", "TEL-001"}, {"purpose", "PUR-001"}],
        supplied = norm(inputs[key]["statement"]),
        actual = norm(get_in(by_id, [id, "statement"])),
        supplied != actual do
      "#{id} statement differs from bootstrap.yaml #{key}: #{inspect(actual)} vs #{inspect(supplied)}"
    end
    |> verdict()
  end

  defp evidence(arts, by_id, m) do
    errs = for a <- arts, a["type"] == "Evidence", err <- evidence_errors(a, by_id, m), do: err
    verdict(errs)
  end

  defp evidence_errors(a, by_id, m) do
    bindings = (a["proposed_bindings"] || []) ++ Enum.map(rels_of(a), & &1["to"])

    [
      a["integrity"] not in m["evidence"]["integrity"] && "#{a["id"]}: invalid integrity",
      a["applicability"] not in m["evidence"]["applicability"] && "#{a["id"]}: invalid applicability",
      bindings == [] && "#{a["id"]}: not bound to any Claim",
      Enum.any?(bindings, &(get_in(by_id, [&1, "type"]) != "Claim")) &&
        "#{a["id"]}: binding target is not an existing Claim",
      a["stage"] == "candidate" and rels_of(a) != [] &&
        "#{a["id"]}: unqualified candidate uses supports/contradicts"
    ]
    |> Enum.filter(& &1)
  end

  defp sources(arts) do
    for a <- arts,
        p = a["provenance"] || %{},
        is_nil(p["created_by"]) or p["inputs"] in [nil, []] do
      "#{a["id"]}: provenance missing created_by or inputs"
    end
    |> verdict()
  end

  defp postconditions(manifest) do
    errs =
      [
        manifest["lifecycle"]["project_state"] != "orienting" && "project_state is not orienting",
        Enum.any?(manifest["canonical_foundation"] || %{}, fn {_, v} -> v != nil end) &&
          "canonical foundation present (expected absent during orientation)"
      ]
      |> Enum.filter(& &1)

    case errs do
      [] -> {:warn, ["deterministic_check: pass cannot be established — scripts/check unimplemented (DEF-008)"]}
      _ -> {:fail, errs}
    end
  end
end

OrientationCheck.run()
